### ISSUE TITLE
Basic Materials: Energy crystal Name

### ISSUE THREAD

**Issue by mazes-80** [technix/ham_radio#2]
I think there's a typo with the following item name and the craft for ham_radio:circuit becomes unusable when basic_materials is active.

`diff --git a/craft.lua b/craft.lua`
`index c81cb1a..849d892 100644`
`--- a/craft.lua`
`+++ b/craft.lua`
`@@ -10,7 +10,7 @@ if minetest.get_modpath("basic_materials") then`
`   body = 'basic_materials:plastic_sheet'`
`   wires = 'basic_materials:copper_wire'`
`   antenna = wires`
`-  battery = 'basic_materials:simple_energy_crystal'`
`+  battery = 'basic_materials:energy_crystal_simple'`
` end`
` `
 `if minetest.get_modpath("technic") then`

**Comment by technix** [comment]
Thank you for reporting this!
Fixed with https://github.com/technix/ham_radio/commit/809c86a18c41467f2dc86f1a5a5067894e297065
