### ISSUE TITLE
transmission range formula

### ISSUE THREAD

**Issue by severak** [technix/ham_radio#3]
I don't understand how power of transmitter is calculated ( in `ham_radio:locate_transmitter`). The formula is unfamiliar to me and I was able to to receive signal from transmitter more than 30000 blocks away from me.

I understand that in real life HAMs are able to pick signals from very long distance but from game perspective I found it little bit boring.

Can you please explain how this formula works?

**Comment by technix** [comment]
Sure!
This formula is a polynomial I created with online polynomial generator. Don't remember which one I used, but, for example, this one can do the job: https://arachnoid.com/polysolve/
I provided desired values for specific points, and generator created a function which gives you smooth graph based on these - so signal power decreases gradually.

Here you can see the graph and how I tried other, simpler, approaches:
https://docs.google.com/spreadsheets/d/1VoQ8IVrwOxH_Dvu4HLN2nckRAF0XXeNP755SNWmYxrc/edit?usp=sharing

So if you want to limit signal distance, you may generate another polynomial which gives you the signal fade curve you need.

**Comment by technix** [comment]
Also, this formula affects only signal strength displayed when using handheld receiver. You still able to receive RDS messages from any transmitter no matter how far it is.
